### ISSUE TITLE
Is README obsolete ?

### ISSUE THREAD

**Issue by vedmaka** [MenaraSolutions/geographer#5]
Is documentation obsolete or i am missing something ?

```
$countries = $earth->getCountries();
$thailand = $countries->findOne(['code' => 'TH']);
```

Will not work because $earth->getCountries() returns **MemberCollection** instance, which has no **findOne** method, only inherited from **Divisible** has it ( Country, City, State ).

**Comment by dusterio** [comment]
You are absolutely right, this was a typo! 

I moved finder methods to Collection class because it makes more sense this way – it's basically array filtering. Divisible still got 'convenience' methods that will call Collection.

So you can now call find() and findOne() on either Collection or Divisible

Thanks for noticing and reporting this
